[package]
edition = "2024"
name = "error-handling"
version = "0.1.0"

[dependencies]
askama = "0.14.0"
axum = "0.8.4"
displaydoc = "0.2.5"
sqlx = { version = "0.8.6", features = ["json"] }
thiserror = "2.0.12"
tower-http = { version = "0.6.6", features = ["normalize-path"] }
